### ISSUE TITLE
希望能增加直接对slice的打包、解包处理

### ISSUE THREAD

**Issue by sohoer1997** [fananchong/cstruct-go#2]
希望能增加直接对slice的打包、解包处理，可以直接出入一个slice对象，不需要将slice对象放入struct中处理

**Comment by fananchong** [comment]
直接对 slice 打包的有很多序列化库，go 官方的就有好几个。不需要额外提供

**Comment by fananchong** [comment]
后续会在 json 定义描述文件中，增加直接支持 []struct 类型字段。
目前变通方法：
type XXX struct {
    a []YYY
}
这样用 struct 包裹下
