### ISSUE TITLE
`[]*struct` 类型反序列化，可能存在 gc 问题

### ISSUE THREAD

**Issue by sohoer1997** [fananchong/cstruct-go#4]
`[]*struct` 类型反序列化，可能存在 gc 问题

**Comment by fananchong** [comment]
修改版本：14ee96d5a7edd2fbda1ea4ba8f3a211cd39a3e6c

**Comment by fananchong** [comment]
修改版本： 14ee96d5a7edd2fbda1ea4ba8f3a211cd39a3e6c

**Comment by fananchong** [comment]
还原了一处优化操作， 7fbc113b5611403d28a5f946fab229750e03cfba
测试下是否是这次优化造成的

**Comment by sohoer1997** [comment]
经测试，是编译参数影响，与 是否 优化操作7fbc113 无关。
